"""empty message

Revision ID: 76d0a756130d
Revises: 
Create Date: 2021-03-22 14:49:14.351080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d0a756130d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=225), nullable=True),
    sa.Column('number_of_bedrooms', sa.String(length=100), nullable=True),
    sa.Column('number_of_bathrooms', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('price', sa.String(length=100), nullable=True),
    sa.Column('typeHA', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('photo', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
